# Default database configuration

development:
  adapter: mysql
  database: rotsen_development
  username: 
  password: 

test:
  adapter: mysql
  database: rotsen_test
  username: 
  password: 
  
production:
  adapter: mysql
  database: rotsen_production
  username: 
  password: 

